### ISSUE TITLE
Add a button to resign a game

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#123]
A new button named **Resign** should be displayed below the PGN movetext section `1.e4 c5` to allow resigning a chess game.

![figure-01](https://user-images.githubusercontent.com/4062000/133575362-8521b3ee-ae17-4ddb-8c3d-929581f8de53.png)

No more programming is required to close this issue — just display the button, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [`testing-redux-chess app`](https://github.com/chesslab/testing-redux-chess) in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by ahmedibrahim404** [comment]
Hi, Can you assign me this issue?

**Comment by programarivm** [comment]
@ahmedibrahim404, welcome to ChesslabLab.

Thank you for joining the community.

Happy learning and coding!

Keep it up.

**Comment by ahmedibrahim404** [comment]
@programarivm 
Thanks!
I just pushed my PR, waiting for your reply.

**Comment by programarivm** [comment]
I really like the PR, it's been easy to review.

Thank you,

**Comment by ahmedibrahim404** [comment]
I am glad to hear that
Sorry, can you add label 'hacktoberfest-accepted' for this issue so that it can be counted for me as an accepted one?

**Comment by programarivm** [comment]
Good point, probably that is okay as per [Hacktoberfest rules](https://hacktoberfest.digitalocean.com/):

> A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label.

Anyway https://github.com/chesslablab/redux-chess/pull/137 has been given the `hacktoberfest-accepted` label. 

A few more issues are to be published within the next few days. 

Thank you, and stay tuned.
