### ISSUE TITLE
Add a button to offer a draw

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#124]
A new button named **Offer draw** should be displayed below the PGN movetext section `1.e4 c5` to allow offering a draw to the opponent. 

![figure-01](https://user-images.githubusercontent.com/4062000/133573243-12f93ef5-85c7-4cfe-b8af-6f34ab7c5328.png)

No more programming is required to close this issue — just display the button, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [`testing-redux-chess`](https://github.com/chesslab/testing-redux-chess) app in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by Divyateja04** [comment]
I would like to work on this...can you provide some more info about this?

**Comment by programarivm** [comment]
Hello @Divyateja04, 

Welcome to ChesslabLab!

Probably the first thing to do is set up and run the [Redux Chess Testing Application](https://github.com/chesslablab/testing-redux-chess) on your computer.

Don't be discouraged if it looks like it is too complicated or takes too much time, because the project may be quite challenging for any React newbie. I'd recommend to take it easy especially in the beginning, and learn one step at a time.

Also, please read the [How to Contribute](https://medium.com/geekculture/how-to-contribute-to-chesslab-cca73fefaf70) guidelines.

By the way, this issue is supposed to be assigned from October 1st because it is a Hacktoberfest issue.

I can't wait to see what you come up with.

Happy learning and coding!

**Comment by Divyateja04** [comment]
Sure I'll check it out, but can you also assign this to me in the meanwhile so that no one else works on this....if I feel I won't be able to do it I promise I'll reassign myself

**Comment by programarivm** [comment]
@Divyateja04 [this issue](https://github.com/chesslablab/redux-chess/issues/132) has been created and assigned to you. 

It's very similar to https://github.com/chesslablab/redux-chess/issues/124 -- in fact that's how lichess.org is implementing its UI -- which should be assigned from October 1st.

Sorry about that, please let me know if this is okay.

Happy learning and coding!

**Comment by Divyateja04** [comment]
yeah sure...I'll check it out

**Comment by Divyateja04** [comment]
This button should be displayed beside the Request a takeback button or below the whole papers element?

**Comment by programarivm** [comment]
Good question, probably it should be displayed between the **Request a takeback** button as per https://github.com/chesslablab/redux-chess/pull/134 and the **Resign** button as per https://github.com/chesslablab/redux-chess/pull/137. 

A few more issues are to be published within the next days; for example, the three new buttons should be displayed into a button group, but that'll be a different issue if that's okay.

Thank you, and stay tuned.

**Comment by programarivm** [comment]
Yes, no problem. Thanks!

**Comment by Divyateja04** [comment]
Sent a PR to offer a draw, I assume next issue is to display a dialog or will we work on the previous dialog to make sure it displays on the other opponent's side?

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/redux-chess/pull/140

Nice! Easy to review after closing https://github.com/chesslablab/redux-chess/issues/132 and https://github.com/chesslablab/redux-chess/issues/135

Thank you,

**Comment by Divyateja04** [comment]
Yeah, thanks for teaching me stuff infact..so um next issue?
