### ISSUE TITLE
Add a button to propose a takeback

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#132]
A new button named **Propose a takeback** should be displayed below the PGN movetext section `1.e4 c5` to allow proposing a takeback to the opponent.

![figure-01](https://user-images.githubusercontent.com/4062000/134534773-8b47e047-ef0b-431a-8255-5dff651632bd.png)

No more programming is required to close this issue — just display the button, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [`testing-redux-chess app`](https://github.com/chesslablab/testing-redux-chess) in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by Divyateja04** [comment]
Hey, should I fork before cloning the repo?

**Comment by programarivm** [comment]
Good point! 

The `testing-redux-chess` repo should be cloned and the `redux-chess` repo forked, if that makes sense. Let me review the docs.

Thank you, and keep it up.

**Comment by Divyateja04** [comment]
Also if you don't mind one more doubt

Projects
->@chesslablab->redux-chess
->testing-redux-chess
Is this how the file structure is supposed to look?

also there's a command called install local(on my terminal and git bash I get install-local not available

**Comment by programarivm** [comment]
I just updated [the docs](https://github.com/chesslablab/testing-redux-chess/blob/master/README.md):

> As you can see, it is required to install the [`install-local`](https://www.npmjs.com/package/install-local) package; for further information please visit [How to Test a Local React NPM Package With Ease](https://javascript.plainenglish.io/testing-a-local-react-npm-package-with-ease-7d0668676ddb).

I hope this will answer your question. 

Thank you!

**Comment by Divyateja04** [comment]
Also um the file structure?

**Comment by Divyateja04** [comment]
Also sorry if I'm troubling you a lot

**Comment by programarivm** [comment]
The folder structure should be like this:

```
$ ls -la
drwxrwxr-x 18 standard standard 4096 sep 18 16:23 .
drwxr-xr-x 56 standard standard 4096 sep 23 16:27 ..
drwxrwxr-x  3 standard standard   25 sep 18 16:00 @chesslablab
drwxrwxr-x  6 standard standard  166 sep 21 18:39 testing-redux-chess
```

**Comment by Divyateja04** [comment]
um you have discord or something or do I just ask my queries here itself?

**Comment by Divyateja04** [comment]
Okay done with that..next how do I install the chess server...that link there doesn't have any instructions
https://github.com/chesslablab/chess-server

**Comment by programarivm** [comment]
That sounds good! 

Now the easiest thing to do is use the sandbox server for testing purposes if you don't want to run the chess server locally. 

In this case, please update the `src/index.js` file as it is described next.

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Chess } from '@chesslablab/redux-chess';

const props = {
  server: {
    prot: 'wss',
    host: 'pchess.net',
    port: '8443'
  }
};

ReactDOM.render(
  <Chess props={props} />,
  document.getElementById('redux-chess')
);
```
However, the sandbox server might not be up and running all the time.

No discord server, sorry.

**Comment by programarivm** [comment]
The [PHP Chess Server docs](https://github.com/chesslablab/chess-server) should provide a few more details because atm it's assumed the reader already knows some PHP. I'll have a look at the docs tomorrow.

Thank you!

**Comment by Divyateja04** [comment]
yeah I'll change the index.js....should I run npm start or just wait for updates to be done to the php docs...and yeah thanks to you too for helping me

**Comment by programarivm** [comment]
That's okay. With everything installed, [this command](https://github.com/chesslablab/testing-redux-chess#start-the-testing-app) should start the testing application in Linux.

**Comment by Divyateja04** [comment]
Yeah but I didn't download php yet..so I'll check out tomorrow too

**Comment by programarivm** [comment]
The [docs](https://github.com/chesslablab/chess-server) were improved to describe step by step how to run the chess server locally. Thanks!

**Comment by Divyateja04** [comment]
yeah I downloaded php and chess server and now I got that chess server is running then realized I didn't need to have this running in order to test using the sandbox server and now I tried to run this

```
npm run publish:npm --prefix ../@chesslablab/redux-chess && npm run update:local:redux-chess && npm start
``` 
This gave me some random errors probably due to me using powershell so I tried to run them separately 
```
npm run publish:npm --prefix ../@chesslablab/redux-chess
```
And then it tells me rm is not an internal or external command
Doubt 1 - So um what do I do here?

Doubt 2 - in the [docs](https://github.com/chesslablab/testing-redux-chess#start-the-testing-app) it says cd into testing-redux-chess I think this is unnecessary and leads to more confusion...and also instead of saying /home/standard/projects/ you should say "location of the @chesslablab" folder so that everyone can use it

**Comment by programarivm** [comment]
At this moment it's primarily intended to run on Unix-based operating systems.

**Comment by Divyateja04** [comment]
ohhhhhhhhh um is there any way I can do this without a unix like OS?
Like I just had to add a button component so does that require everything too
Can't I just run npm start without focusing much on the back end and work on it

**Comment by programarivm** [comment]
That's a good point, the following two commands may not run on Windows:  

```
$ npm run publish:npm --prefix /home/standard/projects/@chesslablab/redux-chess && npm run update:local:redux-chess && npm start
```

```
$ npm run publish:npm --prefix /home/standard/projects/@chesslablab/redux-chess && npm run update:local:redux-chess && npm run restart --port=3000
```

Possibly it is a good idea to find the equivalent commands on Windows and run them separately; it'd be nice if those could be shared as well. 

The important thing is to know what's running under the hood I suppose.

Happy learning and coding!

**Comment by Divyateja04** [comment]
Yeah I'll look into it and get back to you if I figure it out...also um why isn't this issue tagged hacktoberfest though?

**Comment by Divyateja04** [comment]
Also as far as ik the problem is in the package.json itself you are using unix specific code which means we need to change those itself which probably can make issues for you

**Comment by programarivm** [comment]
What about [installing and using the Linux bash shell on Windows](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) by the way?

**Comment by Divyateja04** [comment]
Hey, the easiest solution I found was using git bash(Maybe add it into your docs too)

Now I am not getting any errors except probably I missed something in the file structure

**Comment by Divyateja04** [comment]
So um since you closed this, I assume I irritated you by asking too many questions...if I did...I'm really sorry

**Comment by programarivm** [comment]
Windows users may want to install the Windows Subsystem for Linux aka [WSL](https://docs.microsoft.com/en-us/windows/wsl/):

```
wsl --install
```

**Comment by programarivm** [comment]
Sorry if I closed this issue by mistake.

**Comment by Divyateja04** [comment]
Oh I was thinking I was asking too many questions

**Comment by programarivm** [comment]
That's okay, now the app is set up and running on Windows.

I can't wait to see what you come up with, happy learning and coding!

**Comment by Divyateja04** [comment]
Nope it's not yet running lol, I think I messed up something....but I'll figure it out and get back to you and um can you add the hacktoberfest tag to this too(seriously no offence just asking)

**Comment by Divyateja04** [comment]
![image](https://user-images.githubusercontent.com/28446977/134698581-c54f4b18-5bc3-4e49-af0d-cbce8d5232fb.png)
Moment of Truth!!!

This works I assume there's no AI on the other side running right?
(Like I'm asking to know if it's not working or it's not there at all)

Also now I'm supposed to add a button to which code, the ```testing-redux-chess``` or ```@chesslablab/redux-chess```

**Comment by programarivm** [comment]
Looks good!

The button is to be added to the `@chesslablab/redux-chess` package, btw remember to [restart the testing app](https://github.com/chesslablab/testing-redux-chess#restart-the-testing-app) in order to see the changes in the browser.

There's no AI button yet, however there's an [AI in the PHP Chess library](https://github.com/chesslablab/php-chess#play-chess-with-an-ai).

Sorry but the hacktoberfest tags are supposed to be assigned from October 1st.

Keep it up.

**Comment by Divyateja04** [comment]
oh that's okay I was just asking and yeah I'll try adding buttons and get back to you

And about hacktoberfest I was just asking normally

**Comment by Divyateja04** [comment]
![image](https://user-images.githubusercontent.com/28446977/134713330-f7cc39eb-0077-4c86-a982-a2409431eb59.png)
Hey finally done with a button(Adding took less time than the time needed to configure it lol)

**Comment by programarivm** [comment]
Let me just point out two things:

- **Takeback** should be replaced with **Propose a takeback**
- Remeber to send the PR as per the [contributing guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md)

Well done! This is a really good first issue in my opinion because setting up the full-stack environment may not be too obvious.

**Comment by Divyateja04** [comment]
1. Yeah sure
2. Sure you want me to PR now itself though or I'll work on some things during hacktoberfest and PR all of them together maybe work on the Draw buttons too(not now, I meant in october only)

**Comment by programarivm** [comment]
This one can be PRed.

Thanks!

**Comment by Divyateja04** [comment]
PRed

**Comment by programarivm** [comment]
It looks like the PR is one step away from being merged. 

Let me point out that the button should be displayed in **Invite a friend** mode only, as it is shown in the GIF attached.

![input](https://user-images.githubusercontent.com/4062000/134778154-e1bde57d-4883-4c7a-953e-c6afa429fd7f.gif)

I'll be happy to guide you through the process of displaying the button in **Invite a friend** mode. If that's okay, may I ask to install the [Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension) in your browser?

Thanks!

**Comment by programarivm** [comment]
Possibly the [docs](https://github.com/chesslablab/testing-redux-chess) should mention that the [Redux DevTools Extension](https://github.com/zalmoxisus/redux-devtools-extension) should be installed in order to debug the app.

**Comment by Divyateja04** [comment]
Um the docs didn't say it but yeah I will install it and you can guide me

**Comment by Divyateja04** [comment]
installed it what next?

**Comment by programarivm** [comment]
Okay, let's review the PR within the next few days. 

The **Propose a takeback** button should be displayed inside an `if` statement when `mode.current` equals `playfriend` and `mode.playfriend.accepted` is `true`, as shown in the following example.

![figure-01](https://user-images.githubusercontent.com/4062000/134779010-70f3d3d2-0013-4724-bdf2-a9a86f7af328.png)

**Comment by Divyateja04** [comment]
Yeah but this if statement can't be written in the same file as chess.js since it's inside the return element so I create a new file?
If yes, what do I name it?

**Comment by programarivm** [comment]
Let's review it specifically within the next few days.

However the `if` statement can be written in the `return` element, for example: [`src/components/CreateInviteCodeDialog.js`](https://github.com/chesslablab/redux-chess/blob/master/src/components/CreateInviteCodeDialog.js)

**Comment by Divyateja04** [comment]
Yeah I'll check it out

**Comment by Divyateja04** [comment]
I tried using it, it said state not defined, I then defined state in a similar way to the one in createinvitecodedialog.js

```
  const state = useSelector(state => state);
{
(!state.board.mate && state.mode.playfriend.accepted) ?
  <Button variant="outlined">Propose a Takeback</Button> :
  null
}
```

but I got some Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

**Comment by programarivm** [comment]
Probably the main `Chess.js` component should remain completely declarative so that the programmer can easily rearrange the components inside. 

If this is okay, please copy and paste the following changes from commit [`bd31cd7a2e5a0b30b53278d1755a556513d0069b`](https://github.com/chesslablab/redux-chess/commit/bd31cd7a2e5a0b30b53278d1755a556513d0069b) into your branch, and let's merge the PR.

Happy learning and coding!

**Comment by Divyateja04** [comment]
Yeah done!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/redux-chess/pull/134

**Comment by Divyateja04** [comment]
Yay!, Finally done, so I can work on this during hacktoberfest(I mean other simplr issues) as well right?

**Comment by programarivm** [comment]
@Divyateja04 you may want to [Display a dialog asking to accept or cancel a takeback #135](https://github.com/chesslablab/redux-chess/issues/135) if this is okay. Thanks!
