### ISSUE TITLE
Allow to move chess pieces with a mouse drag and drop

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#133]
At the present moment the chess pieces are moved with two mouse clicks: One mouse click on the piece to be moved and another mouse click on the destination square. However, pieces should also be moved with a mouse drag and drop as it is shown in the following example.

![input](https://user-images.githubusercontent.com/4062000/134680833-26827ba7-a6ad-46ef-b665-2695a8b6b554.gif)
**Figure 1**. Pieces should also be moved with a mouse drag and drop.

**Comment by programarivm** [comment]
@DenysLins the documentation has been improved, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Hopefully the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app should be easier to setup.

Thank you and keep it up!

**Comment by programarivm** [comment]
This one may not be too obvious. 

Probably this issue can be elaborated on within the next days in a similar way as with https://github.com/chesslablab/redux-chess/issues/132

Let me know if you have any questions.

Thanks!

**Comment by DenysLins** [comment]
OK @programarivm

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/redux-chess/pull/143
