### ISSUE TITLE
Add a new option to display the FEN string

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#139]
A new option named **FEN** should be added to the ⚙ **Settings** menu to display the FEN string representation of a chess position -- and allow copying it to the clipboard.

![figure-01](https://user-images.githubusercontent.com/4062000/135653350-1f9bb169-2973-43f2-bd1b-53ddecfa61f2.png)

Some programming is required to close this issue. After clicking on the **FEN** option, a dialog will be displayed showing the FEN -- for which a `/fen` request should be first sent to the chess server to fetch the FEN string representation.

Happy coding and learning!

**Comment by programarivm** [comment]
@ahmedibrahim404 if you'd want to look at this issue throughout October please give a ping and it'll be assigned to you if this is okay.

Anyway, thank you and keep it up.

**Comment by ahmedibrahim404** [comment]
Okay sure, I will work into that

**Comment by programarivm** [comment]
Thanks! 

The [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md) as well as https://github.com/chesslablab/redux-chess/issues/132 should guide you through solving this issue.

Please let us know if you have any questions.

Happy learning.

**Comment by ahmedibrahim404** [comment]
@programarivm 
Sorry, but can you provide me with more info about this?
if I have the current chess position in state (last row in history), why i need to send a request to the server to get the FEN?

**Comment by programarivm** [comment]
Hello, here's a hint to solve this issue.

As you may probably know, a pseudo-FEN string (a [shortened FEN string](https://github.com/chesslablab/php-chess/blob/master/src/FEN/ShortenedStringToPgn.php)) is temporarily stored in `board.fen` just before making a chess move which is to say just before leaving a piece on the board. Thus, `board.fen` is always `null` after making a chess move, as it is shown in **Figure 1**.

![figure-01](https://user-images.githubusercontent.com/4062000/135721698-9ff58bd3-a4bb-41ce-bad6-2c9e0a89a973.png)
**Figure 1**. `board.fen` is set to null after making a chess move.

In this particular example, the React app sends the `/playfen "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w"` command to the chess server for validation, as shown in **Figure 2**. 

![figure-02](https://user-images.githubusercontent.com/4062000/135721687-230d983a-6c21-48bd-b658-129079f555b0.png)
**Figure 2**. The shortened FEN string is sent to the server with the `/playfen` command.

Finally, a validated, [standard FEN string](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) is sent back to the React app accordingly, as shown in **Figure 3**.

![figure-03](https://user-images.githubusercontent.com/4062000/135721970-dbd13e32-bbfc-4991-bcd7-e55186db9825.png)
**Figure 3**. `/playfen` response sent to the React app

More specifically:
```
{
  "turn": "b",
  "legal": true,
  "check": false,
  "mate": false,
  "movetext": "1.e4 e5",
  "fen": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6"
}
```

Thus, it is the standard FEN string which should be displayed when clicking on the new option in ⚙ **Settings**.

```
rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6
```

Please let me know if this makes any sense.

Thank you, and happy learning!

**Comment by ahmedibrahim404** [comment]
Okay, I got that.
I attached below a gif showing the feature, let me know your opinion, and also if there is anything needs to be changed before I make the PR
Thanks
@programarivm 
![chrome-capture](https://user-images.githubusercontent.com/34144004/135724561-3d697fd8-45c1-4657-bb3d-7c8cb8554c26.gif)

**Comment by programarivm** [comment]
Well done! I really like this GIF. 

Thank you,

**Comment by ahmedibrahim404** [comment]
Thanks
I pushed the PR, waiting for you comments
@programarivm

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/redux-chess/pull/144
