### ISSUE TITLE
Display buttons in a button group

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#141]
The buttons **Propose a takeback**, **Offer draw** and **Resign** should be displayed in the same line as a button group. It seems as if they all should be added to the [`components/ButtonsPlayFriendMode.js`](https://github.com/chesslablab/redux-chess/blob/master/src/components/ButtonsPlayFriendMode.js) component actually in **Play with a friend** mode only. Also the buttons should be resized to a small size and the text displayed in lowercase.

No more programming is required to close this issue, let's just rearrange the buttons [with ease and joy](https://javascript.plainenglish.io/looking-forward-to-testing-react-components-with-joy-5bb3f86c21d7) I suppose one step at a time.

Keep it up, and happy coding and learning!

![figure-01](https://user-images.githubusercontent.com/4062000/135711362-2e48c661-83d8-4f38-b7ce-3ed668858b60.png)

**Comment by Divyateja04** [comment]
Honestly, I'm impressed with your articles!
They are pretty good and here's the PR
Sending it your way!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/redux-chess/pull/142

**Comment by Divyateja04** [comment]
Yay! Is there another issue we can look into?

**Comment by programarivm** [comment]
At the present moment you may want to look at https://github.com/chesslablab/redux-chess/issues/145

Thanks!

**Comment by Divyateja04** [comment]
lol we are back to the takeback issue, I'll look into it though
