### ISSUE TITLE
Add a test to check that the Load PGN dialog is opened

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#239]
The new test is to be written in `src/__tests__/components/Chess.test.js` and should be similar to that one checking the **Invite a friend** dialog is opened when the `createInviteCodeDialogActions.OPEN` action is dispatched.

Example:

```js
...

it("opens the 'Invite a friend' dialog", () => {
  const action = { type: createInviteCodeDialogActions.OPEN };
  const { result } = renderHook(() => SyncDispatcher(action), { wrapper });
  expect(result.current.state.createInvitationDialog.open).toBe(true);
});

...
```

```
 PASS  src/__tests__/components/Chess.test.js
  Chess
    ✓ opens the 'Invite a friend' dialog (25 ms)
    ○ skipped is rendered
    ○ skipped the first chess board square is a black rook before flipping the chess board
    ○ skipped the first chess board square is a white rook after flipping the chess board

Test Suites: 1 passed, 1 total
Tests:       3 skipped, 1 passed, 4 total
Snapshots:   0 total
Time:        4.549 s, estimated 6 s
Ran all test suites matching /Chess.test.js/i with tests matching "Invite a friend".

Watch Usage: Press w to show more.
```
Keep it up, and happy coding and learning!

**Comment by EndBug** [comment]
Hi, I'd like to open a PR for this issue in the next days, could you assign this to me? Thanks :)

**Comment by programarivm** [comment]
@EndBug welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!
