### ISSUE TITLE
Rename the main menu option Play with the computer

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#243]
The main menu option **Play With the Computer** should be replaced with **Training**.

Keep it up, and happy learing!

**Comment by billymoroney1** [comment]
Hi there, happy learning and coding!

I put in a PR for this -

**Comment by programarivm** [comment]
@billymoroney welcome to ChesslabLab, thank you for joining the community.

Keep it up, and happy learning and coding!
