### ISSUE TITLE
Fix the chess opening search by ECO code

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#247]
At this moment, the chess openings can be searched by code by querying the API. To do so, users have to first select a main ECO code and then click on the **Search** button as it is shown in the GIF below.

![figure-01](https://user-images.githubusercontent.com/4062000/150344489-f8a5c4b1-7a36-472a-bdf5-51b19ad6182e.gif)
**Figure 1**. Searching openings by ECO code.

However, the openings should get fetched and displayed just when the select value is changed — as a result the **Search** button is removed. For further information please visit:

- [Chess API](https://app.swaggerhub.com/apis-docs/chesslablab/chess-rest_api/1.0.0#/Chess%20API/post_opening)

Happy coding!

**Comment by verbindolai** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
Hi @verbindolai, welcome to ChesslabLab.

Thank you for joining the community. Let me introduce myself. My name is Jordi, and I'm a web dev tyring to improve who mentors web devs who're trying to improve as well. Be the first to [sponsor this issue](https://github.com/sponsors/programarivm?frequency=one-time) and let's work together on this one.

Alternatively, please feel free to comment on any of the following non-sponsored issues so that they can be assigned to you:

- [Add a text input box to allow chatting with the opponent #240](https://github.com/chesslablab/redux-chess/issues/240)
- [Add a test to check that the Load PGN dialog is opened #239](https://github.com/chesslablab/redux-chess/issues/239)

Keep it up, and happy learning and coding!

**Comment by verbindolai** [comment]
Should an api call for the initial value also happen on opening the ECO-Code Dialog? If making the call only when changing the value, you would need to reselect the already selected initial value to get the results, dont you?

**Comment by programarivm** [comment]
> Should an api call for the initial value also happen on opening the ECO-Code Dialog?

What about just adding a new option called **Select an option**? This one should be the default one when opening the dialog — with no initial API call happening.

> If making the call only when changing the value, you would need to reselect the already selected initial value to get the results.

The call should be made when the selected value is changed, I hope [this discussion](https://stackoverflow.com/questions/28868071/onchange-event-using-react-js-for-drop-down) will help.

I can't wait to see what you come up with!
