### ISSUE TITLE
Step back button in "Training like a grandmaster" causes bugs

### ISSUE THREAD

**Issue by ADD1609** [chesslablab/redux-chess#251]
Steps to reproduce:

1. Click on the "Training" button and pick any color
2. Make any kind of move
3. Press either one of the two buttons on the top left to step back the game state
![Chess4](https://user-images.githubusercontent.com/91988666/150390830-98f58281-8bd9-448f-b64d-5c3f0a88b798.png)
4. Press either the "Analysis Board" or the "Training" button in the navbar

For me this leads to the following error:
![Chess3](https://user-images.githubusercontent.com/91988666/150391300-ce72fea1-faa0-4ce5-8a99-b9c74f0acb98.png)

**Comment by programarivm** [comment]
@ADD1609, welcome to ChesslabLab. Thank you for joining the community.

Keep it up, and happy learning and coding!
