### ISSUE TITLE
Display a loading indicator when searching ECO codes

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#255]
At this moment, no AJAX loading indicator gets displayed when searching openings with **Opening Search > ECO Code**, which may appear confusing especially if the request takes longer than expected.

Keep it up, and happy learning.

**Comment by shikhar13012001** [comment]
I would like to work on this issue, Can you please assign this to me?

**Comment by programarivm** [comment]
@shikhar13012001 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by shikhar13012001** [comment]
Thankyou for assigning me, could you navigate to the files where the fetching of moves take place and where Ihave to put a loading spinner?

**Comment by programarivm** [comment]
Thanks for asking this question.

The first ajax loader was added today, and it will be a good example to start with. Please see https://github.com/chesslablab/redux-chess/issues/254.  

It seems as though a new Redux flow has to be implemented; thus, described below are the steps to follow:

1. Add a new constant file called `src/constants/ajaxLoader/chessOpeningSearchEcoActionTypes.js`
2. Add a new reducer file called `src/reducers/chessOpeningSearchEcoAjaxLoaderReducer.js`
3. Add a new component file called `src/components/AjaxLoader/ChessOpeningSearchEcoAjaxLoader.js`

The new files should be quite similar to:

- [src/constants/ajaxLoader/chessOpeningAnalysisAjaxLoaderActionTypes.js](https://github.com/chesslablab/redux-chess/blob/master/src/constants/ajaxLoader/chessOpeningAnalysisAjaxLoaderActionTypes.js)
- [src/reducers/chessOpeningAjaxLoaderReducer.js](https://github.com/chesslablab/redux-chess/blob/master/src/reducers/chessOpeningAjaxLoaderReducer.js)
- [src/components/AjaxLoader/ChessOpeningAnalysisAjaxLoader.js](https://github.com/chesslablab/redux-chess/blob/master/src/components/AjaxLoader/ChessOpeningAnalysisAjaxLoader.js)

Don't forget to update `src/components/Chess.js` and `src/reducers/rootReducer.js` accordingly by the way.

And finally, the `chessOpeningSearchEcoActionTypes.CLOSE` and `chessOpeningSearchEcoActionTypes.SHOW` actions are to be dispatched in `src/components/Dialog/OpeningSearchEcoDialog.js`.

Keep it up, and happy coding and learning.

**Comment by shikhar13012001** [comment]
Sure thing, Thanks @programarivm

**Comment by programarivm** [comment]
This is how the Redux flow is implemented in `src/components/OpeningSearchEcoDialog.js`:

```js
...

const OpeningSearchEcoDialog = () => {
  ...

  const handleSearch = (event) => {
    event.preventDefault();
    dispatch({ type: chessOpeningSearchEcoActionTypes.SHOW });
    fetch('https://pchess.net/api/opening', {
      method: 'POST',
      body: JSON.stringify({ eco: event.target.elements.code.value })
    }).then(res => res.json())
      .then(res => {
        setOpenings(res);
        dispatch({ type: chessOpeningSearchEcoActionTypes.HIDE });
      });
  }

  ...
}

export default OpeningSearchEcoDialog;
```

Happy coding!
