### ISSUE TITLE
Restructure the constants folder

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#267]
A new folder called `src/constants/dialog` should be created and all dialog files moved into it as described next:  

```
🗁 src
  🗁 constants
    🗁 dialog
      🗎 createInviteCodeDialogActionTypes.js
      🗎 drawAcceptDialogActionTypes.js
      ...
      🗎 takebackAcceptDialogActionTypes.js
      🗎 takebackOfferDialogActionTypes.js
```

Also please make sure to update the files affected by this change.

Keep it up, and happy learning and coding!

**Comment by Amit91848** [comment]
Checkout my pr #272
