### ISSUE TITLE
Own Server instead of intended PHP

### ISSUE THREAD

**Issue by OmegaHawkeye** [chesslablab/redux-chess#275]
Hello, 

great Repo but I got a question.

Can u use your own Django/Node Server instead of the intended PHP Server? 

Also did u plan to update/upgrade to redux-toolkit and if so how can I help?

Thx in advance, OmegaHawkeye

**Comment by programarivm** [comment]
Hi @OmegaHawkeye, thanks for raising this issue.

Sure, any other chess server can be used as long as it is implementing the actions defined in [`src/actions/serverActions.js`](https://github.com/chesslablab/redux-chess/blob/master/src/actions/serverActions.js).

At this moment `redux-toolkit` is not being used, anyway if you'd want to be assigned an issue please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by OmegaHawkeye** [comment]
Thx for your quick response. 

Do u have any guide/blog to how the server code works cause I'm not the best in PHP?

I will look into the Contributing Guidelines and mby I will work on it.

Thx in advance OmegaHawkeye

**Comment by programarivm** [comment]
Hey @OmegaHawkeye,

Redux Chess is available for download [on the NPM registry](https://www.npmjs.com/package/@chesslablab/redux-chess). Also PHP is not actually required if using the sandbox server on `pchess.net` as described below:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Chess } from '@chesslablab/redux-chess';

const props = {
  server: {
    prot: 'wss',
    host: 'pchess.net',
    port: '8443'
  }
};

ReactDOM.render(
  <Chess props={props} />,
  document.getElementById('redux-chess')
);
```

Keep it up, and happy learning and coding.
