### ISSUE TITLE
Allow to browse chess games by clicking on the moves

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#300]
At the present moment chess games can only be browsed by clicking on the history buttons, however, they can't be browsed by clicking on the moves as it is shown in the image attached.

![output](https://user-images.githubusercontent.com/4062000/159553785-53a7b562-8c6c-496a-8639-2e8b6e152285.gif)

Keep it up, and happy learning.

**Comment by traciingu** [comment]
Hi there, would like to give this a try. Happy learning and coding!

**Comment by programarivm** [comment]
@traciingu welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
Hi @traciingu, did you have a chance to look into the issue?

**Comment by traciingu** [comment]
@programarivm I've never worked with PHP before and am having trouble with this issue. It may be better if I unassigned myself from this one

**Comment by programarivm** [comment]
Thanks anyway, the project is quite challenging. Happy coding and learning.
