### ISSUE TITLE
Allow to select a chess variant when playing online

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#347]
At this moment, the dialog shown below is displayed if clicking on the **Play Online** button.

![figure-01](https://user-images.githubusercontent.com/4062000/192241297-82999e2c-1b77-4348-b3a8-f1dc2279e5b2.png)
Figure 1. Click on **Play Online**

However, a new MUI [TextField](https://mui.com/material-ui/react-text-field/) component with a `select` prop needs to be added to the [src/features/dialog/PlayOnlineDialog.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/dialog/PlayOnlineDialog.js) file in order to allow users select a chess variant:

- Classical
- Chess 960

No more programming is required to close this issue — just display the TextField component with the new two options, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by suryansh-bhatnagar** [comment]
Hey i would love to contribute to your repository. Can you assign this issue to me ??

**Comment by programarivm** [comment]
@suryansh-bhatnagar welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by suryansh-bhatnagar** [comment]
@programarivm can you tell me how to setup it in local??

**Comment by programarivm** [comment]
Redux Chess is an NPM package ready to [npm install](https://www.npmjs.com/package/@chesslablab/redux-chess), and two repos are used to solve issues actually:

- [Redux Chess](https://github.com/chesslablab/redux-chess)
- [Redux Chess Testing Application](https://github.com/chesslablab/testing-redux-chess)

Once you're done with a particular task on Redux Chess, you'll typically need to review it locally as described in [Refresh the Testing App](https://github.com/chesslablab/testing-redux-chess#refresh-the-testing-app).

Keep it up, and happy coding and learning!

**Comment by suryansh-bhatnagar** [comment]
@programarivm  hey can you write a documentation on how to set up it locally after clonning redux-chess
