### ISSUE TITLE
Allow to select a chess variant when playing a friend

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#348]
At this moment, the dialog shown below is displayed if clicking on the **Play a Friend** button.

![figure-01](https://user-images.githubusercontent.com/4062000/192244305-c4c769d3-54ec-4381-b0c8-cf708b2e3f3c.png)
Figure 1. Click on **Play a Friend**

However, a new MUI [TextField](https://mui.com/material-ui/react-text-field/) component with a `select` prop needs to be added to the [src/features/dialog/CreateInviteCodeDialog.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/dialog/CreateInviteCodeDialog.js) file in order to allow users select a chess variant:

- Classical
- Chess 960

No more programming is required to close this issue — just display the TextField component with the new two options, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by jchrobakk** [comment]
Hi there, happy learning and coding!

**Comment by jchrobakk** [comment]
Can you assign this task to me?

**Comment by programarivm** [comment]
@jchrobakk welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!
