### ISSUE TITLE
Allow to select a chess variant when analyzing a PGN movetext

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#349]
At this moment, the dialog shown below is displayed if clicking on **Analysis Board > PGN Movetext**.

![figure-01](https://user-images.githubusercontent.com/4062000/192246702-8168028f-f14c-4991-b78f-dd22ad3e8414.png)
Figure 1. Click on **Analysis Board > PGN Movetext**

However, a new MUI [TextField](https://mui.com/material-ui/react-text-field/) component with a `select` prop needs to be added to the [src/features/dialog/LoadPgnDialog.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/dialog/LoadPgnDialog.js) file in order to allow users select a chess variant:

- Classical
- Chess 960

No more programming is required to close this issue — just display the TextField component with the new two options, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by Arnav-Negi** [comment]
Hi! I would like to work on this, please assign it to me if possible.

**Comment by programarivm** [comment]
@Arnav-Negi welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by Sumitmaithani** [comment]
hey, I'm mern stack developer if there is new issues and bugs to be fixed please let me know.

**Comment by programarivm** [comment]
@Sumitmaithani welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
