### ISSUE TITLE
Allow to select a chess variant when analyzing a FEN string

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#350]
At this moment, the dialog shown below is displayed if clicking on **Analysis Board > FEN String**.

![figure-01](https://user-images.githubusercontent.com/4062000/192248626-8f97c5ac-93db-4a7c-8ef6-679812e6cb82.png)
Figure 1. Click on **Analysis Board > FEN String**

However, a new MUI [TextField](https://mui.com/material-ui/react-text-field/) component with a `select` prop needs to be added to the [src/features/dialog/LoadFenDialog.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/dialog/LoadFenDialog.js) file in order to allow users select a chess variant:

- Classical
- Chess 960

No more programming is required to close this issue — just display the TextField component with the new two options, it's a really good first issue to get familiar with the codebase! It is intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Happy learning and coding, and keep it up.

**Comment by rutvikk05** [comment]
Hello, I would like to work on this issue. Could you please assign it to me?

**Comment by programarivm** [comment]
@rutvikk05 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by rutvikk05** [comment]
Hey @programarivm , I'm finding it difficult to start the chess server from my system. I can't sudo-apt Stockfish in Gitbash, so I've installed the stockfish engine manually. When I start the server, here's the error I get : 


![Screenshot (235)](https://user-images.githubusercontent.com/78073642/194888024-5208d38e-06ed-4546-afe2-757d049d879c.png)

**Comment by programarivm** [comment]
@rutvikk05 the `players.json` file is to be generated with the command line tools available in the [Chess Data](https://github.com/chesslablab/chess-data) repo, however, the repo has been updated right now. Please [click here](https://github.com/chesslablab/chess-server/blob/master/data/players.json) to obtain a copy of `players.json` or run `git pull origin master`.

Alternatively, you may want to connect to `pchess.net` as in [the demo](https://github.com/programarivm/demo-redux-chess/blob/master/src/App.js) rather than installing the chess server locally.

```js
import { CssBaseline, Grid } from '@mui/material';
import { Chess } from '@chesslablab/redux-chess';
import Footer from './Footer';

const App = () => {
  return (
    <>
      <CssBaseline />
      <Grid container style={{ marginTop: 15 }}>
        <Grid item md={12}>
          <Chess props={{
            api: {
              prot: 'https',
              host: 'pchess.net',
              port: '443'
            },
            server: {
              prot: 'wss',
              host: 'pchess.net',
              port: '8443'
            }
          }}
          />
        </Grid>
        <Grid item md={12}>
          <Footer />
        </Grid>
      </Grid>
    </>
  );
}

export default App;
```

For further information please visit:

- [Chess\Grandmaster](https://php-chess.readthedocs.io/en/latest/grandmaster/)

Keep it up, and happy learning and coding!

**Comment by rutvikk05** [comment]
Thanks for clarifying the previous issue, @programarivm . 
I've now  included the players.json file, but unable to execute send on the websocket. Tweaked a bit of the code, only to give a different error. 
![Screenshot (236)](https://user-images.githubusercontent.com/78073642/195076365-94f5e048-2ef9-45a6-984f-79d09e743fc0.png)

**Comment by programarivm** [comment]
Thanks for the feedback, [the docs](https://github.com/chesslablab/chess-server) have been updated just now.

A variant along with a mode must be provided to start a game as it is described next:

```
const ws = new WebSocket('wss://pchess.net:8443');
ws.onmessage = (res) => { console.log(res.data) };
ws.send('/start classical analysis');
```

Keep it up, and happy coding!

**Comment by rutvikk05** [comment]
I've tried it, but it's still giving the same error :(
![Screenshot (237)](https://user-images.githubusercontent.com/78073642/195248729-06637798-9a0a-4f84-bab1-5ce16701e21f.png)

**Comment by programarivm** [comment]
Have you tried to debug the app with [websocat](https://github.com/vi/websocat) by the way? 

Alternatively, you may want to use the sandbox server at `pchess.net` rather than setting it up on your local machine.

```
const ws = new WebSocket('wss://pchess.net:8443');
ws.onmessage = (res) => { console.log(res.data) };
ws.send('/start classical analysis');
```
This will hopefully allow to keep the focus on the frontend side.

Keep it up and happy learning!

**Comment by rutvikk05** [comment]
Hey @programarivm, I've done the necessary changes in the file. But I'm unable to test them as I can't start the server locally. 
Would Sandbox server help me reflect those changes? If so, how do I set it up? 
Thanks for your patience, btw :D

**Comment by programarivm** [comment]
Redux Chess is an NPM package ready to [npm install](https://www.npmjs.com/package/@chesslablab/redux-chess), and two repos are used to solve issues actually:

- [Redux Chess](https://github.com/chesslablab/redux-chess)
- [Redux Chess Testing Application](https://github.com/chesslablab/testing-redux-chess)

Once you're done with a particular task on Redux Chess, it typically needs to be reviewed locally as described in [Refresh the Testing App](https://github.com/chesslablab/testing-redux-chess#refresh-the-testing-app).

Keep it up, and happy coding and learning!

**Comment by programarivm** [comment]
Thanks @rutvikk05 for the help, 

Now that I've looked into this issue I just realized it's not necessary to select a chess variant when analyzing a FEN string.

![fen](https://user-images.githubusercontent.com/4062000/199605221-21934399-6b4f-4fae-95c7-52a03c463e07.gif)

However, for PGN analysis a chess variant must be selected.

![output_trimmed_enhanced](https://user-images.githubusercontent.com/4062000/199605260-caf20667-3d35-4390-a83b-56f5514d750a.gif)

See https://github.com/chesslablab/redux-chess/issues/349

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
Finally after putting thougnt into this issue it seems as if a chess variant is indeed required in order to load a FEN string accordingly. 

The issue has been reopened, so let's recap.

Users should be allowed to select a chess variant when loading a FEN string similarly as with loading a PGN movetext.

![figure_01](https://user-images.githubusercontent.com/4062000/222953891-ef88fcaf-967b-4320-9cd1-f26d9bd27b31.png)
Figure 1. **Analysis Board > FEN String**

![figure_02](https://user-images.githubusercontent.com/4062000/222953903-7af0a37a-8538-449b-85b0-3b510b191d04.png)
Figure 2. **Analysis Board > PGN Movetext**

To some extent in terms of the parameters required, this is quite similar to loading a FEN string for image download as recently documented in the [Chess API Reference Guide](https://chesslablab.com/documentation).

![figure_03](https://user-images.githubusercontent.com/4062000/222953962-e175bc1a-40e9-4db4-82c1-83a1cf7c71fe.png)

Figure 3. POST /download_image

See https://github.com/chesslablab/chess-api/blob/main/src/Controller/DownloadImageController.php

Keep it up, and happy coding and learning.
