### ISSUE TITLE
Add Capablanca's pieces

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#351]
Let's implement a new chess variant!

According to Wikipedia:

> Capablanca believed that chess would be played out in a few decades (meaning games between grandmasters would always end in draws).

[Capablanca's pieces](https://en.wikipedia.org/wiki/Capablanca_chess) (archbishop and chancellor) have recently been added to the [src/assets/img/pieces/default/](https://github.com/chesslablab/redux-chess/tree/master/src/assets/img/pieces/default) folder. Now the [src/common/Piece.js](https://github.com/chesslablab/redux-chess/blob/master/src/common/Piece.js) file needs to be updated accordingly.  `' A '` and `' a '` are the strings used to describe the archbishop while `' C '` and `' c '` are to describe the chancellor.

This is a good first issue to get started with the codebase, it's intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Keep it up, and happy learning and coding!

**Comment by AyushK-101** [comment]
I would like to work on this issue

**Comment by programarivm** [comment]
@AyushK-101 welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by Tathagat27** [comment]
Hi @programarivm ! I would like to work on it. Can you please assign it to me.
