### ISSUE TITLE
Display an image representing the selected color

### ISSUE THREAD

**Issue by programarivm** [chesslablab/redux-chess#352]
Redux Chess allows to play chess online with players all over the world. Attached below is the dialog that is dislpayed when users click on the **Play Online** button as long as there are other players waiting to be paired.

![figure-03](https://user-images.githubusercontent.com/4062000/192593394-8eefd251-030d-4ef3-a592-c39c1e70e389.png)
Figure 1. Click on **Play Online**

At this moment, the letter `w` is used to represent the white pieces while the letter `b` represents the black pieces, however, an image should be displayed instead. `w` needs to be replaced with [src/assets/img/pieces/png/150/wKing.png](https://github.com/chesslablab/redux-chess/blob/master/src/assets/img/pieces/png/150/wKing.png) and `b` with [src/assets/img/pieces/png/150/bKing.png](https://github.com/chesslablab/redux-chess/blob/master/src/assets/img/pieces/png/150/bKing.png).

[src/features/table/PlayOnlineTable.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/table/PlayOnlineTable.js) is the file that has to be changed, and below is a hint that will help you solve this issue.

- [src/features/dialog/SelectColorButtons.js](https://github.com/chesslablab/redux-chess/blob/master/src/features/dialog/SelectColorButtons.js)

This is a good first issue to get started with the codebase, it's intended to install and set up the [testing-redux-chess](https://github.com/chesslablab/testing-redux-chess) app in your computer in order to solve more issues.

Keep it up, and happy coding and learning!

**Comment by programarivm** [comment]
@techsnap welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Let me just bring up that the PR for this issue should be sent after October 1 because it's been labelled as hacktoberfest.

I can't wait to see what you come up with!

**Comment by techsnap** [comment]
Hey, I will not be working on this issue since my NPM installation is having a failure.

**Comment by cychu42** [comment]
Hello, I would like to give this issue a go. Would that be fine?

**Comment by cychu42** [comment]
Hi there, happy learning and coding!

**Comment by cychu42** [comment]
Sorry, I should have said that before instead. Please assign this issue to me.
