### ISSUE TITLE
Use functions instead of classes with static functions in common folder

### ISSUE THREAD

**Issue by Nishith-Savla** [chesslablab/redux-chess#355]
Instead of using classes with static functions in the commons folder, I think it's better and cleaner to export just the functions and then import as `import * as Ascii from "./common/Ascii"`

Shall I refactor this?

**Comment by programarivm** [comment]
@Nishith-Savla welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/redux-chess/blob/master/CONTRIBUTING.md).

Sorry about that but at this moment I'm not too sure about replacing the static classes with functions. 

Also thanks for the proposal! 

Please stay tuned, and happy learning and coding.

**Comment by Nishith-Savla** [comment]
Okay, no problem.
